import Head from "next/head";
import type { NextPage } from "next";
import styles from "../../styles/Home.module.css";
import { User } from "prisma/typegraphql/generated/models/User";

interface Props {
  currentUser: Omit<User, "password">;
}

const UserPage: NextPage<Props> = (props: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>User Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {props.currentUser
            ? `Welcome back, ${props.currentUser.name}!`
            : "Welcome!"}
        </h1>
        <div>
          Your account was created on{" "}
          {props.currentUser?.createdAt.toDateString()}
        </div>
      </main>
    </div>
  );
};

export default UserPage;
