import type { GetServerSideProps, NextPage } from "next";
import getCurrentUserFromNextContext from "lib/get_user_from_next_context";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { User } from "prisma/typegraphql/generated/models/User";

interface Props {
  currentUser: User | null;
}

const Home: NextPage<Props> = (props: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Prisma TypeGraphQL Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {props.currentUser
            ? `Welcome back, ${props.currentUser.name}!`
            : "Welcome!"}
        </h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const currentUser = await getCurrentUserFromNextContext({ context });
  return {
    props: {
      currentUser
    }
  };
};

export default Home;
